version: "3.8"

# SERVICES
services:

  # DATABASE
  db:
    build: ./db
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    volumes:
      - ./db:/db
      - db_data:/var/lib/postgresql/data/

  # BACKEND
  api:
    build: ./api
    ports: 
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./api:/api
    command: ./start.sh

  # FRONTEND
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - ./web/.env    
    volumes:
      - ./web:/web
    command: ./start.sh

# VOLUMES
volumes:
  db_data: